services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8888:8888/tcp
      - 8005:8005
      - 8120:8120
      - 8989:8989
      - 7878:7878
      - 8191:8191
      - 9696:9696
      - 32400:32400
    volumes:
      - ./data/gluetun:/gluetun
      - ./data/gluetun/temp:/tmp/gluetun
    environment:
      - DNS_ADDRESS=127.0.0.11
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER:?err}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:?err}
      - SERVER_COUNTRIES=United States
      - SERVER_CITIES=Dallas
      - SERVER_CATEGORIES=P2P
    # networks:
    #  - gluetun

  qbittorrent: 
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes: 
      - ./data/qbittorrent:/config
      - ~/tmp/plex/downloads:/downloads
    environment: 
      - TZ=America/Chicago
      - WEBUI_PORT=8120
      - PUID=1000
      - PGID=1000
      - UMASK=022
    network_mode: "service:gluetun"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Chicago
      - PUID=1001
      - PGID=1000
      - UMASK=022
    volumes:
      - ./data/sonarr/config:/config
      - ~/tmp/plex/downloads:/downloads
      - ~/tmp/plex/tv:/tv
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Chicago
      - PUID=1002
      - PGID=1000
      - UMASK=022
    volumes:
      - ./data/radarr/config:/config
      - ~/tmp/plex/downloads:/downloads
      - ~/tmp/plex/movies:/movies
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Chicago
      - PUID=1003
      - PGID=1000
      - UMASK=022
    volumes:
      - ./data/prowlarr/config:/config
    restart: unless-stopped

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    network_mode: "service:gluetun"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Chicago
      - PUID=1004
      - PGID=1000
      - UMASK=022
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM:?err}
    volumes:
      - ./data/plex/config:/config
      - ~/tmp/plex/movies:/movies
      - ~/tmp/plex/tv:/tv
    restart: unless-stopped
